name: Setup Rust and Stellar
description: Installs Rust toolchain and Stellar CLI
runs:
  using: composite
  steps:
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        targets: wasm32-unknown-unknown

    - name: Install wasm-validate
      run: |
        wget -q https://github.com/WebAssembly/wabt/releases/download/1.0.31/wabt-1.0.31-linux.tar.gz
        tar xvf wabt-1.0.31-linux.tar.gz
        sudo mv wabt-1.0.31/bin/* /usr/local/bin/
        wasm-validate --version
      shell: bash

    - name: Install Stellar CLI
      run: |
        wget -q https://github.com/stellar/stellar-cli/releases/download/v22.2.0/stellar-cli-22.2.0-x86_64-unknown-linux-gnu.tar.gz
        tar xvf stellar-cli-22.2.0-x86_64-unknown-linux-gnu.tar.gz
        sudo mv stellar /usr/local/bin/
        stellar --version
      shell: bash

