name: "Rust: Format Check"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check

  deploy:
    needs: rustfmt
    uses: ./.github/workflows/contract-deploy.yml
