name: "Rust: Format Check"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [trigger-rustfmt]
  workflow_call:

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check

  trigger-deploy:
    needs: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Trigger contract deploy workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-deploy
          client-payload: '{"ref": "${{ github.ref }}"}'
