name: Verify Build
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Rust and Stellar
        uses: ./.github/actions/setup-rust-stellar

      - name: Build contracts
        run: cd contracts/boundless && make build

      - name: Run tests
        run: cargo test --release

  trigger-rustfmt:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rustfmt workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-rustfmt
          client-payload: '{"ref": "${{ github.ref }}"}'
