name: Verify Build
on:
  push:
    branches:
      - main
    paths:
      - 'contracts/**'
      - '.github/workflows/verify-build.yml'
  pull_request_target:
    branches:
      - main
    paths:
      - 'contracts/**'
      - '.github/workflows/verify-build.yml'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Rust and Stellar
        uses: ./.github/actions/setup-rust-stellar

      - name: Build contracts
        run: cd contracts/boundless && make build

      - name: Run tests
        run: cargo test --release

  rustfmt:
    needs: build
    if: success()
    uses: ./.github/workflows/rustfmt.yml
    secrets:
      STELLAR_SECRET_KEY: ${{ secrets.STELLAR_SECRET_KEY }}
      SOROBAN_SECRET_KEY: ${{ secrets.SOROBAN_SECRET_KEY }}
      CONTRACT_ID: ${{ secrets.CONTRACT_ID }}
